/*
 * Generated by web/sync-shipped.cjs from the mod's sounds.json and intro textures.
 * Do not edit by hand. Run directly or through web/sync-assets.sh.
 *
 * A script keeps resource suggestions available when index.html is opened from disk.
 */

const SHIPPED = {
  "sounds": [
    "battle_music.b2w2_tournament",
    "battle_music.corvault",
    "battle_music.default",
    "battle_music.dianthea",
    "battle_music.ivor",
    "battle_music.jacinthe",
    "battle_music.lysandre",
    "battle_music.neoflare",
    "battle_music.rayquaza_mega_za",
    "battle_music.trainer_battle_hgss",
    "battle_music.ultra_necrozma"
  ],
  "textures": [
    "cobblemon-trainers:textures/gui/intro/circle.png",
    "cobblemon-trainers:textures/gui/intro/fond_rerebleue.png",
    "cobblemon-trainers:textures/gui/intro/paint_border.png",
    "cobblemon-trainers:textures/gui/intro/paint_border2.png",
    "cobblemon-trainers:textures/gui/intro/paint_vs.png"
  ]
};
