const fs = require('node:fs');
const path = require('node:path');

const projectRoot = path.resolve(__dirname, '..');

/** Read the actual resources, including textures stored in subfolders. */
function readCatalog(root = projectRoot) {
  const assets = path.join(root, 'common/src/main/resources/assets/cobblemon-trainers');
  const sounds = Object.keys(JSON.parse(fs.readFileSync(path.join(assets, 'sounds.json'), 'utf8'))).sort();
  if (!sounds.length) throw new Error('sync-shipped: sounds.json contains no sound keys');

  const textures = [];
  function visit(folder, relative = '') {
    for (const entry of fs.readdirSync(folder, { withFileTypes: true })) {
      const name = relative + entry.name;
      if (entry.isDirectory()) visit(path.join(folder, entry.name), name + '/');
      else if (entry.isFile() && entry.name.endsWith('.png')) {
        textures.push('cobblemon-trainers:textures/gui/intro/' + name);
      }
    }
  }
  visit(path.join(assets, 'textures/gui/intro'));
  return { sounds, textures: textures.sort() };
}

function renderCatalog(catalog) {
  return `/*
 * Generated by web/sync-shipped.cjs from the mod's sounds.json and intro textures.
 * Do not edit by hand. Run directly or through web/sync-assets.sh.
 *
 * A script keeps resource suggestions available when index.html is opened from disk.
 */

const SHIPPED = ${JSON.stringify(catalog, null, 2)};
`;
}

if (require.main === module) {
  const catalog = readCatalog();
  fs.writeFileSync(path.join(__dirname, 'js/shipped.js'), renderCatalog(catalog));
  console.log(`web/js/shipped.js: ${catalog.textures.length} textures, ${catalog.sounds.length} sounds`);
}

module.exports = { readCatalog, renderCatalog };
